### PR TITLE
Create login page

### LINKED ISSUE #74: login html page

### PR DESCRIPTION
**Pull request by MadeleineKRoberts**
## Describe your changes
closes #74 
Create login html page
Adds route to login page to nav bar
Translates page to Spanish

## Non-obvious technical information
Iniciar sesión that appears twice in the Spanish version is fixed in #76. Log in and sign up were translated wrong. 

## Checklist before requesting a review
- [X] pre-commit run --all-files (run before pushing)
- [X] pytest if applicable
- [X] Link issue
- [x] Update relevant documentation if applicable: doc strings, readme, poetry.

```commandline
HERE IS SOME COMMAND LINE OUTPUT
```

image

image

### CODE REVIEW

**Review by sumslong — DISMISSED** [review]

**Review by sumslong — CHANGES_REQUESTED** [review]
After merging the sign-up page, there are now merge conflicts that need to be resolved.

**Comment by MadeleineKRoberts** [comment]
> After merging the sign-up page, there are now merge conflicts that need to be resolved.

resolving rn 🫡

**Review by MadeleineKRoberts — COMMENTED** [review]
Fixed merge issue

**Review by MadeleineKRoberts — COMMENTED** [review]
Viewed

**Review by sumslong — APPROVED** [review]

**Pull request merged**
